stages:
  - nuget

nuget:
  stage: nuget
  only:
    - master
  script:
    - dotnet pack ./src/AsyncMapper/ -o publish --include-symbols
    - dotnet nuget push $NUGET_FOLDER/*symbols.nupkg -s $NUGET_URL -k nuget:nuget