stages:
  - nuget

nuget:
  stage: nuget
  only:
    - master
  script:
    - powershell
    - dotnet pack ./src/AsyncMapper/ -o publish --include-symbols
    - powershell
    - dir ./publish
    - dotnet nuget push ./publish/*symbols.nupkg -s $NUGET_URL -k nuget:nuget