stages:
  - build
  - nuget-push

build:
  stage: build
  only:
    - master
  script:
    - powershell
    - dotnet pack ./src/AsyncMapper/ -o publish --include-symbols
    - dotnet pack ./src/AsyncMapper.DependencyInjection/ -o publish --include-symbols

nuget-push:
  stage: nuget-push
  script:
    - Get-ChildItem -Path ./publish -Filter "*symbols.nupkg" | ForEach-Object { dotnet nuget push $_.FullName -s "${NUGET_URL}" -k nuget:nuget }

